### ISSUE TITLE
TrainFunction() just take one parameter for validation

### ISSUE THREAD

**Issue by gianluigilopardo** [luciainnocenti/German-Credit-Data#2]
I'm not sure about the TrainFunction(): does it only assumes to validate one parameter for each model?

**Comment by luciainnocenti** [comment]
> I'm not sure about the TrainFunction(): does it only assumes to validate one parameter for each model?

It's a wrapper function: you select the model and the dataset and the function executes the training phase and the evaluation one. In this case I decided, for each model, to fix all the parameters but one.
